package dat3.cars.service;

import dat3.cars.dto.CarRequest;
import dat3.cars.dto.CarResponse;
import dat3.cars.dto.MemberRequest;
import dat3.cars.dto.MemberResponse;
import dat3.cars.entity.Car;
import dat3.cars.entity.Member;
import dat3.cars.repository.MemberRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;


import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.ArgumentMatchers.any;

@ExtendWith(MockitoExtension.class)
class MemberServiceMockitoTest {
    @Mock
    MemberRepository memberRepository;

    MemberService memberService;

    Member m1;
    Member m2;

    @BeforeEach
    void setUp() {
        m1 = new Member("m1", "test12", "m1@a.dk", "bb", "Olsen", "xx vej 34", "Lyngby", "2800");
        m2 = new Member("m2", "test12", "m2@a.dk", "aa", "hansen", "xx vej 34", "Lyngby", "2800");
        memberService = new MemberService(memberRepository);
    }


    @Test
    void testGetMembersAdmin() {

        m1.setCreated(LocalDateTime.now());
        m2.setCreated(LocalDateTime.now());

        Mockito.when(memberRepository.findAll()).thenReturn(List.of(m1,m2));

        List<MemberResponse> members = memberService.getMembers(true);
        assertEquals(2,members.size());
        assertNotNull(members.get(0).getCreated());
    }

    @Test
    void testGetMembersNotAdmin() {
        // Init test members with creation dates
        m1.setCreated(LocalDateTime.now());
        m2.setCreated(LocalDateTime.now());

        Mockito.when(memberRepository.findAll()).thenReturn(List.of(m1,m2));
        List<MemberResponse> members = memberService.getMembers(true);
        assertEquals(2,members.size());
        assertNotNull(members.get(0).getCreated());
    }


    @Test
    void testGetMembers() {
        m1.setCreated(LocalDateTime.now());
        m2.setCreated(LocalDateTime.now());
        List<Member> members = new ArrayList<>();
        members.add(m1);
        members.add(m2);
        Mockito.when(memberRepository.findAll()).thenReturn(members);

        List<MemberResponse> memberResponses = memberService.getMembers(true);
        assertEquals(2,memberResponses.size());
        assertEquals("m1",memberResponses.get(0).getUsername());
        assertEquals("m2",memberResponses.get(1).getUsername());
        assertEquals("m1@a.dk",memberResponses.get(0).getEmail());
        assertEquals("m2@a.dk",memberResponses.get(1).getEmail());
        assertEquals("bb",memberResponses.get(0).getFirstName());
        assertEquals("aa",memberResponses.get(1).getFirstName());
        assertEquals("Olsen",memberResponses.get(0).getLastName());
        assertEquals("hansen",memberResponses.get(1).getLastName());
        assertEquals("xx vej 34",memberResponses.get(0).getStreet());
        assertEquals("xx vej 34",memberResponses.get(1).getStreet());
        assertEquals("Lyngby",memberResponses.get(0).getCity());
        assertEquals("Lyngby",memberResponses.get(1).getCity());
        assertEquals("2800",memberResponses.get(0).getZip());
        assertEquals("2800",memberResponses.get(1).getZip());
    }

    @Test
    void addMember() {
        Member newMember = new Member("newMember", "test12", "m1@a.dk", "bb", "Olsen", "xx vej 34", "Lyngby", "2800");
        //If Id was generated by the server, for example as for car you would need to set the id here
        Mockito.when(memberRepository.save(any(Member.class))).thenReturn(newMember);

        //Quick way to get a MemberRequest (remember eventually values come via a incoming JSON object)
        MemberRequest request = new MemberRequest(newMember);
        MemberResponse response = memberService.addMember(request);
        assertEquals("m1@a.dk", response.getEmail());
    }

    @Test
    void editMember(){
        m1.setCreated(LocalDateTime.now());
    }
    @Test
    void testEditMember() {

        Member newMember = new Member("newMember", "test123", "m3@a.dk", "cc", "Jensen", "yy vej 56", "Copenhagen", "1000");

        Mockito.when(memberRepository.save(any(Member.class))).thenReturn(newMember);
        Mockito.when(memberRepository.findById("newMember")).thenReturn(Optional.of(newMember));

        Member updatedMember = new Member("newMember", "test456", "m3edited@a.dk", "dd", "Tikøbsen", "zz vej 44", "Roskilde", "4000");

        MemberRequest memberRequest = new MemberRequest(updatedMember);

        if (memberRequest != null){
            MemberResponse editedMemberResult = memberService.updateMember(memberRequest, "updatedMember");

            assertNotNull(editedMemberResult);
            assertEquals("test456", editedMemberResult.getPassword());
            assertEquals("m3edited@a.dk", editedMemberResult.getEmail());
            assertEquals("dd", editedMemberResult.getFirstName());
            assertEquals("Tiksen", editedMemberResult.getLastName());
            assertEquals("zz vej 44", editedMemberResult.getStreet());
            assertEquals("Roskilde", editedMemberResult.getCity());
            assertEquals("4000", editedMemberResult.getZip());
        }
    }


    @Test
    void testDeleteMember() {
        Member member = new Member("m1", "test12", "m1@a.dk", "bb", "Olsen", "xx vej 34", "Lyngby", "2800");

        Mockito.when(memberRepository.findById("m1")).thenReturn(Optional.of(member));

        memberService.deleteMember("m1");

        Mockito.verify(memberRepository, Mockito.times(1)).delete(member);
    }

}