package dat3.cars.service;

import dat3.cars.dto.MemberRequest;
import dat3.cars.dto.MemberResponse;
import dat3.cars.entity.Member;
import dat3.cars.repository.MemberRepository;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;


import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.ArgumentMatchers.any;

@ExtendWith(MockitoExtension.class)
class MemberServiceMockitoTest {
    @Mock
    MemberRepository memberRepository;

    MemberService memberService;

    @BeforeEach
    void setUp() {
        memberService = new MemberService(memberRepository);
    }

    @Test
    void getMembersAdmin() {
        Member m1 = new Member("m1", "m1@a.dk", "test12", "bb", "Olsen", "xx vej 34", "Lyngby", "2800");
        Member m2 = new Member("m2", "m2@a.dk", "test12", "aa", "hansen", "xx vej 34", "Lyngby", "2800");
        m1.setCreated(LocalDateTime.now());
        m2.setCreated(LocalDateTime.now());

        Mockito.when(memberRepository.findAll()).thenReturn(List.of(m1,m2));

        List<MemberResponse> members = memberService.getMembers(true);
        assertEquals(2,members.size());
        assertNotNull(members.get(0).getCreated());
    }

    @Test
    void getMembersNotAdmin() {
        // Create test members
        Member m1 = new Member("m1", "m1@a.dk", "test12", "bb", "Olsen", "xx vej 34", "Lyngby", "2800");
        Member m2 = new Member("m2", "m2@a.dk", "test12", "aa", "hansen", "xx vej 34", "Lyngby", "2800");
        // Init test members with creation dates
        m1.setCreated(LocalDateTime.now());
        m2.setCreated(LocalDateTime.now());

        Mockito.when(memberRepository.findAll()).thenReturn(List.of(m1,m2));
        List<MemberResponse> members = memberService.getMembers(true);
        assertEquals(2,members.size());
        assertNotNull(members.get(0).getCreated());
    }

    @Test
    void addMember() {
        Member m1 = new Member("m1", "test12", "m1@a.dk", "bb", "Olsen", "xx vej 34", "Lyngby", "2800");
        //If Id was generated by the server, for example as for car you would need to set the id here
        Mockito.when(memberRepository.save(any(Member.class))).thenReturn(m1);

        //Quick way to get a MemberRequest (remember eventually values come via a incoming JSON object)
        MemberRequest request = new MemberRequest(m1);
        MemberResponse response = memberService.addMember(request);
        assertEquals("m1@a.dk",response.getEmail());
    }


    @Test
    void getMembers() {
        List<Member> members = new ArrayList<>();
        members.add(new Member("m1", "test12", "m1@a.dk", "bb", "Olsen", "xx vej 34", "Lyngby", "2800"));
        members.add(new Member("m2", "test12", "m2@a.dk", "aa", "hansen", "xx vej 34", "Lyngby", "2800"));
        Mockito.when(memberRepository.findAll()).thenReturn(members);

        List<MemberResponse> memberResponses = memberService.getMembers(true);
        assertEquals(2,memberResponses.size());
        assertEquals("m1",memberResponses.get(0).getUsername());
        assertEquals("m2",memberResponses.get(1).getUsername());
        assertEquals("m1@a.dk",memberResponses.get(0).getEmail());
        assertEquals("m2@a.dk",memberResponses.get(1).getEmail());
        assertEquals("bb",memberResponses.get(0).getFirstName());
        assertEquals("aa",memberResponses.get(1).getFirstName());
        assertEquals("Olsen",memberResponses.get(0).getLastName());
        assertEquals("hansen",memberResponses.get(1).getLastName());
        assertEquals("xx vej 34",memberResponses.get(0).getStreet());
        assertEquals("xx vej 34",memberResponses.get(1).getStreet());
        assertEquals("Lyngby",memberResponses.get(0).getCity());
        assertEquals("Lyngby",memberResponses.get(1).getCity());
        assertEquals("2800",memberResponses.get(0).getZip());
        assertEquals("2800",memberResponses.get(1).getZip());
    }

    @Test
    void deleteMember() {
        Member member = new Member("m1", "test12", "m1@a.dk", "bb", "Olsen", "xx vej 34", "Lyngby", "2800");

        Mockito.when(memberRepository.findById("m1")).thenReturn(Optional.of(member));

        memberService.deleteMember("m1");

        Mockito.verify(memberRepository, Mockito.times(1)).delete(member);
    }

}